<?php

namespace Container33pANLy;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_OdNhAMEService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.OdNhAME' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.OdNhAME'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'App\\Controller\\DepotController::depotCompte' => ['privates', '.service_locator.Oj1FpDm', 'get_ServiceLocator_Oj1FpDmService', true],
            'App\\Controller\\TransactionController::codeTransaction' => ['privates', '.service_locator.D6tjQl2', 'get_ServiceLocator_D6tjQl2Service', true],
            'App\\Controller\\TransactionController::depotUser' => ['privates', '.service_locator.raYkoSo', 'get_ServiceLocator_RaYkoSoService', true],
            'App\\Controller\\TransactionController::retraitUser' => ['privates', '.service_locator.NsAIhVr', 'get_ServiceLocator_NsAIhVrService', true],
            'App\\Controller\\UserController::addUser' => ['privates', '.service_locator.E1M71Bm', 'get_ServiceLocator_E1M71BmService', true],
            'App\\Controller\\UserController::addUserAgence' => ['privates', '.service_locator.E1M71Bm', 'get_ServiceLocator_E1M71BmService', true],
            'App\\Controller\\UserController::connected' => ['privates', '.service_locator.Wnnvhqc', 'get_ServiceLocator_WnnvhqcService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'App\\Kernel::terminate' => ['privates', '.service_locator.KfwZsne', 'get_ServiceLocator_KfwZsneService', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'kernel::terminate' => ['privates', '.service_locator.KfwZsne', 'get_ServiceLocator_KfwZsneService', true],
            'App\\Controller\\DepotController:depotCompte' => ['privates', '.service_locator.Oj1FpDm', 'get_ServiceLocator_Oj1FpDmService', true],
            'App\\Controller\\TransactionController:codeTransaction' => ['privates', '.service_locator.D6tjQl2', 'get_ServiceLocator_D6tjQl2Service', true],
            'App\\Controller\\TransactionController:depotUser' => ['privates', '.service_locator.raYkoSo', 'get_ServiceLocator_RaYkoSoService', true],
            'App\\Controller\\TransactionController:retraitUser' => ['privates', '.service_locator.NsAIhVr', 'get_ServiceLocator_NsAIhVrService', true],
            'App\\Controller\\UserController:addUser' => ['privates', '.service_locator.E1M71Bm', 'get_ServiceLocator_E1M71BmService', true],
            'App\\Controller\\UserController:addUserAgence' => ['privates', '.service_locator.E1M71Bm', 'get_ServiceLocator_E1M71BmService', true],
            'App\\Controller\\UserController:connected' => ['privates', '.service_locator.Wnnvhqc', 'get_ServiceLocator_WnnvhqcService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'kernel:terminate' => ['privates', '.service_locator.KfwZsne', 'get_ServiceLocator_KfwZsneService', true],
        ], [
            'App\\Controller\\DepotController::depotCompte' => '?',
            'App\\Controller\\TransactionController::codeTransaction' => '?',
            'App\\Controller\\TransactionController::depotUser' => '?',
            'App\\Controller\\TransactionController::retraitUser' => '?',
            'App\\Controller\\UserController::addUser' => '?',
            'App\\Controller\\UserController::addUserAgence' => '?',
            'App\\Controller\\UserController::connected' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'App\\Kernel::terminate' => '?',
            'kernel::loadRoutes' => '?',
            'kernel::registerContainerConfiguration' => '?',
            'kernel::terminate' => '?',
            'App\\Controller\\DepotController:depotCompte' => '?',
            'App\\Controller\\TransactionController:codeTransaction' => '?',
            'App\\Controller\\TransactionController:depotUser' => '?',
            'App\\Controller\\TransactionController:retraitUser' => '?',
            'App\\Controller\\UserController:addUser' => '?',
            'App\\Controller\\UserController:addUserAgence' => '?',
            'App\\Controller\\UserController:connected' => '?',
            'kernel:loadRoutes' => '?',
            'kernel:registerContainerConfiguration' => '?',
            'kernel:terminate' => '?',
        ]);
    }
}
