<?php

namespace Container33pANLy;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getComptePersisterService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\DataPersister\ComptePersister' shared autowired service.
     *
     * @return \App\DataPersister\ComptePersister
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/DataPersister/ComptePersister.php';

        return $container->privates['App\\DataPersister\\ComptePersister'] = new \App\DataPersister\ComptePersister(($container->services['doctrine.orm.default_entity_manager'] ?? $container->getDoctrine_Orm_DefaultEntityManagerService()));
    }
}
