<?php

namespace Container33pANLy;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getDepotPersisterService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\DataPersister\DepotPersister' shared autowired service.
     *
     * @return \App\DataPersister\DepotPersister
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/DataPersister/DepotPersister.php';

        return $container->privates['App\\DataPersister\\DepotPersister'] = new \App\DataPersister\DepotPersister(($container->services['doctrine.orm.default_entity_manager'] ?? $container->getDoctrine_Orm_DefaultEntityManagerService()));
    }
}
