<?php

namespace ContainerK5nHf61;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_E1M71BmService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.E1M71Bm' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.E1M71Bm'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'encoder' => ['services', 'security.password_encoder', 'getSecurity_PasswordEncoderService', true],
            'serializer' => ['services', '.container.private.serializer', 'get_Container_Private_SerializerService', false],
            'validator' => ['privates', 'api_platform.validator', 'getApiPlatform_ValidatorService', true],
        ], [
            'encoder' => '?',
            'serializer' => '?',
            'validator' => '?',
        ]);
    }
}
