<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerBBZjyzW\App_KernelTestDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerBBZjyzW/App_KernelTestDebugContainer.php') {
    touch(__DIR__.'/ContainerBBZjyzW.legacy');

    return;
}

if (!\class_exists(App_KernelTestDebugContainer::class, false)) {
    \class_alias(\ContainerBBZjyzW\App_KernelTestDebugContainer::class, App_KernelTestDebugContainer::class, false);
}

return new \ContainerBBZjyzW\App_KernelTestDebugContainer([
    'container.build_hash' => 'BBZjyzW',
    'container.build_id' => 'b0087068',
    'container.build_time' => 1614604822,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerBBZjyzW');
