<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container33pANLy\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container33pANLy/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container33pANLy.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container33pANLy\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container33pANLy\App_KernelDevDebugContainer([
    'container.build_hash' => '33pANLy',
    'container.build_id' => '8fade418',
    'container.build_time' => 1616546029,
], __DIR__.\DIRECTORY_SEPARATOR.'Container33pANLy');
