<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerK5nHf61\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerK5nHf61/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerK5nHf61.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerK5nHf61\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerK5nHf61\App_KernelDevDebugContainer([
    'container.build_hash' => 'K5nHf61',
    'container.build_id' => '1e09e2cf',
    'container.build_time' => 1614804141,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerK5nHf61');
