<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerLCshxxI\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerLCshxxI/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerLCshxxI.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerLCshxxI\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerLCshxxI\App_KernelDevDebugContainer([
    'container.build_hash' => 'LCshxxI',
    'container.build_id' => 'b623d545',
    'container.build_time' => 1616094094,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerLCshxxI');
